name: Publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: build it and publish it
      env:
        S3_ID: ${{ secrets.S3_ID }}
        S3_SECRET: ${{ secrets.S3_SECRET }}
        JEKYLL_ENV: production
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
        bundle exec s3_website push
